web/dbpatterns/api/urls.py
from django.conf.urls import patterns, url, include

from documents.resources import DocumentResource
from comments.resources import CommentResource
from profiles.resources import UserResource

urlpatterns = patterns('',

    url(r'^', include(DocumentResource().urls)),
    url(r'^', include(CommentResource().urls)),

    # django views
    url(r'^users/$', UserResource.as_view()),

)

web/dbpatterns/blog/urls.py
from django.conf.urls import patterns, url

from blog.sitemaps import BlogSitemap
from blog.views import BlogDetailView, BlogIndexView, \
                        BlogPostsRssFeed, BlogPostsAtomFeed


urlpatterns = patterns('',

    # blog urls
    url(r'^$', BlogIndexView.as_view(), name="blog"),
    url(r'^(?P<slug>[-\w]+)/$', BlogDetailView.as_view(), name="blog_detail"),

    # rss & atom feed
    url(r'^feed/rss$', BlogPostsRssFeed(), name="blog_rss_feed"),
    url(r'^feed/atom', BlogPostsAtomFeed(), name="blog_atom_feed"),

    # sitemap
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {
            "blog": BlogSitemap()
        }}, name="blog_sitemap"),

)

web/dbpatterns/documents/urls.py
from django.conf.urls import patterns, url

from documents.views import (DocumentDetailView, ExportDocumentView,
                             DocumentForksView, DocumentStarsView,
                             NewDocumentView, MyDocumentsView, DocumentEditView,
                             ForkDocumentView, StarDocumentView,
                             SearchDocumentView)

urlpatterns = patterns(
    '',
    url(r'^$', MyDocumentsView.as_view(), name='my_documents'),
    url(r'^search$', SearchDocumentView.as_view(), name='search_document'),
    url(r'^new$', NewDocumentView.as_view(), name='new_document'),
    url(r'^(?P<slug>[-\w]+)/$', DocumentDetailView.as_view(),
        name='show_document'),
    url(r'^(?P<slug>[-\w]+)/forks$', DocumentForksView.as_view(),
        name='show_document_forks'),
    url(r'^(?P<slug>[-\w]+)/stars', DocumentStarsView.as_view(),
        name='show_document_stars'),
    url(r'^(?P<slug>[-\w]+)/export/(?P<exporter>[-\w]+)$',
        ExportDocumentView.as_view(), name='export_document'),
    url(r'^(?P<slug>[-\w]+)/edit$', DocumentEditView.as_view(),
        name='edit_document'),
    url(r'^(?P<slug>[-\w]+)/fork$', ForkDocumentView.as_view(),
        name='fork_document'),
    url(r'^(?P<slug>[-\w]+)/star$', StarDocumentView.as_view(),
        name='star_document'),

)

web/dbpatterns/profiles/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from profiles.views import (RegistrationView, LoginView, LogoutView,
                            ProfileDetailView)


urlpatterns = patterns('',

    url(r'^login/$', LoginView.as_view(template_name="auth/login.html"), name='auth_login'),
    url(r'^logout/$', LogoutView.as_view(), name='auth_logout'),
    url(r'^register/$', RegistrationView.as_view(
        template_name="auth/register.html"), name='auth_registration'),
    url(r'^complete/$', TemplateView.as_view(
        template_name="auth/complete.html"), name='auth_registration_complete'),
    url(r'^profile/(?P<username>[\w\._-]+)/$', ProfileDetailView.as_view(
        template_name="auth/profile.html"), name='auth_profile'),

)

web/dbpatterns/profiles/models.py
from django.db import models
from django.contrib.auth.models import AnonymousUser, User
from django.utils.encoding import smart_unicode


class AnonymousProfile(AnonymousUser):
    username = "AnonymousUser"
    email = ""

    def get_full_name(self):
        return self.username


class FollowedProfile(models.Model):
    """
    A relationship model for following users
    """
    follower = models.ForeignKey(User, related_name="following")
    following = models.ForeignKey(User, related_name="followers")

    def __unicode__(self):
        return smart_unicode("%s following %s" % (self.follower.username,
                                                  self.following.username))

web/dbpatterns/documents/forms.py
from django import forms
from django.forms import RadioSelect

from documents.fields import SearchInput
from documents.parsers import ParseError
from documents.parsers.django_orm import DjangoORMParser
from documents.parsers.dummy import DummyParser

DOCUMENT_PARSER_BLANK = ""
DOCUMENT_PARSER_DJANGO_ORM = "django-orm"

DOCUMENT_PARSER_CHOICES = (
    (DOCUMENT_PARSER_BLANK, "Empty Document"),
    (DOCUMENT_PARSER_DJANGO_ORM, "Django Models"),
)

DOCUMENT_PARSERS = {
    DOCUMENT_PARSER_BLANK: DummyParser,
    DOCUMENT_PARSER_DJANGO_ORM: DjangoORMParser
}

EXAMPLE_DJANGO_MODEL = """
class Foo(models.Model):
    bar = models.CharField(max_length=255)


class Bar(models.Model):
    foo =  models.CharField(max_length=255)
"""


class DocumentForm(forms.Form):
    title = forms.CharField(label="Document title")
    is_public = forms.BooleanField(
        widget=forms.RadioSelect(
            choices=[(True, 'Public'), (False, 'Private')]),
        required=False,
        initial=True,
        label="The visibility of document")
    create_from = forms.CharField(
        label="Create from",
        widget=forms.Select(choices=DOCUMENT_PARSER_CHOICES),
        required=False)
    entities = forms.CharField(
        label="Template",
        widget=forms.Textarea(),
        initial=EXAMPLE_DJANGO_MODEL,
        required=False)
    # TODO: The initial value solution is temporary. Change it.

    def clean_entities(self):
        create_from = self.cleaned_data.get("create_from")
        if create_from:
            try:
                parser_class = DOCUMENT_PARSERS[create_from]
            except KeyError:
                raise forms.ValidationError("Invalid parser.")
            else:
                parser = parser_class(self.cleaned_data.get("entities"))
            try:
                parser.is_valid()
            except ParseError:
                raise forms.ValidationError("Syntax error.")
            else:
                return parser.parsed
        return []


class ForkDocumentForm(forms.Form):
    title = forms.CharField(label="Document title")


class SearchForm(forms.Form):
    keyword = forms.CharField(
        widget=SearchInput(placeholder="Type a keyword"))

web/dbpatterns/profiles/forms.py
from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ("username", "email")

web/dbpatterns/blog/views.py
from django.conf import settings
from django.contrib.syndication.views import Feed
from django.utils.feedgenerator import Atom1Feed
from django.views.generic import ListView
from django.views.generic.detail import DetailView

from blog.models import Post


class BlogIndexView(ListView):
    template_name = "blog/index.html"
    queryset = Post.published_objects.all()
    context_object_name = "posts"
    paginate_by = 30


class BlogDetailView(DetailView):
    template_name = "blog/detail.html"
    model = Post
    context_object_name = "post"

    def get_queryset(self):
        if self.request.user.is_superuser:
            return self.model.objects.all()
        return self.model.published_objects.all()


class BlogPostsRssFeed(Feed):
    title = settings.BLOG_FEED_TITLE
    link = settings.BLOG_URL
    description = settings.BLOG_FEED_DESCRIPTION

    def items(self):
        return Post.objects.all()[:20]

    def item_description(self, post):
        return post.content

    def item_pubdate(self, post):
        return post.date_created

    def item_categories(self, post):
        return [tag.name for tag in post.tags.all()]


class BlogPostsAtomFeed(BlogPostsRssFeed):
    feed_type = Atom1Feed
    subtitle = settings.BLOG_FEED_DESCRIPTION

web/dbpatterns/documents/views.py
from datetime import datetime
from itertools import imap

from bson import ObjectId

from django.core.urlresolvers import reverse
from django.utils.http import urlencode
from django.views.generic import TemplateView, FormView, ListView, RedirectView, View
from django.conf import settings
from django import http

from tastypie.http import HttpNoContent

from blog.models import Post
from profiles.mixins import LoginRequiredMixin
from newsfeed.models import Entry
from newsfeed.constants import *
from documents.constants import *
from documents.forms import DocumentForm, ForkDocumentForm, SearchForm
from documents.mixins import DocumentMixin
from documents.models import Document
from documents.resources import DocumentResource
from documents.utils import extract_keywords
from documents.signals import (document_done, fork_done, star_done,
                               document_delete, fork_delete)
from documents.exporters.sql import (MysqlExporter, PostgresExporter,
                                     SQLiteExporter, OracleExporter)


DOCUMENT_EXPORTERS = {
    EXPORTER_MYSQL: MysqlExporter,
    EXPORTER_POSTGRES: PostgresExporter,
    EXPORTER_SQLITE: SQLiteExporter,
    EXPORTER_ORACLE: OracleExporter,
}


class HomeView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        if self.request.user.is_anonymous():
            is_public = True
        else:
            is_public = self.request.GET.get("public") == "true"
        try:
            page_number = int(self.request.GET.get("page"))
        except (ValueError, TypeError):
            page_number = 1

        newsfeed = self.get_newsfeed(
            public=is_public,
            offset=NEWSFEED_LIMIT * (page_number - 1))

        if NEWSFEED_LIMIT * page_number < newsfeed.count():
            next_page_url = self.get_next_page_url(self.request, page_number)
        else:
            next_page_url = None

        return {
            "is_public": is_public,
            "newsfeed": imap(Entry, newsfeed),
            "next_page_url": next_page_url,
            "featured_documents": self.get_featured_documents(),
            "starred_documents": self.get_starred_documents(),
            "latest_posts": self.get_latest_posts(),
            "search_form": SearchForm()
        }

    def get_featured_documents(self):
        return Document.objects.featured()

    def get_starred_documents(self):
        if self.request.user.is_anonymous():
            return []
        return Document.objects.starred(user_id=self.request.user.id)

    def get_newsfeed(self, public=True, offset=0, limit=NEWSFEED_LIMIT):
        """
        Fetches news items from the newsfeed database
        """
        parameters = {
            "news_type": {
                "$in": [NEWS_TYPE_REGISTRATION,
                        NEWS_TYPE_COMMENT,
                        NEWS_TYPE_DOCUMENT,
                        NEWS_TYPE_FORK,
                        NEWS_TYPE_STAR,
                        NEWS_TYPE_FOLLOWING]
            }}

        if not public:
            parameters["recipients"] = {
                "$in": [self.request.user.pk]
            }

        newsfeed = Entry.objects.collection.find(
            parameters).sort([("date_created", -1)])

        return newsfeed[offset:offset + limit]

    def get_next_page_url(self, request, page_number):
        """
        Builds the next page link from GET parameters.
        """
        return "%(newsfeed_url)s?%(parameters)s" % {
            "newsfeed_url": reverse("home"),
            "parameters": urlencode({
                "public": request.GET.get("public") or "false",
                "page": page_number + 1
            })}

    def get_latest_posts(self):
        return Post.objects.all()[:10]


class DocumentDetailView(DocumentMixin, TemplateView):
    template_name = "documents/show.html"

    def get_context_data(self, **kwargs):
        return {"document": self.get_document(),
                "exporters": EXPORTERS}


class ExportDocumentView(DocumentMixin, View):

    def get(self, *args, **kwargs):
        klass = DOCUMENT_EXPORTERS.get(kwargs.get("exporter"))
        if klass is None:
            return http.HttpResponseBadRequest()
        document = self.get_document()
        exporter = klass(document)
        return http.HttpResponse(exporter.as_text(), content_type="text/plain")


class DocumentForksView(DocumentDetailView):
    template_name = "documents/forks.html"

    def get_context_data(self, **kwargs):
        context = super(DocumentForksView, self).get_context_data(**kwargs)
        context["forks"] = context.get("document").forks()
        return context


class DocumentStarsView(DocumentDetailView):
    template_name = "documents/stars.html"


class StarDocumentView(LoginRequiredMixin, RedirectView, DocumentMixin):

    def post(self, request, *args, **kwargs):
        document = self.get_document()
        stars = document.get_stars()
        if request.user.pk in stars:
            stars.remove(request.user.pk)
        else:
            stars.append(request.user.pk)
            star_done.send(sender=self, instance=document,
                           user=request.user)
        Document.objects.collection.update(
            {"_id": document.pk},
            {"$set": {"stars": stars, "star_count": len(stars)}})

        return super(StarDocumentView, self).post(request, *args, **kwargs)

    def get_redirect_url(self, **kwargs):
        return reverse("show_document", args=[self.kwargs.get("slug")])


class DocumentEditView(LoginRequiredMixin, DocumentDetailView):
    template_name = "documents/edit.html"

    def get(self, request, *args, **kwargs):
        if not self.is_authorized():
            return self.redirect()

        return super(DocumentEditView, self).get(request, *args, **kwargs)

    def delete(self, *args, **kwargs):
        if not self.is_authorized():
            return self.redirect()

        document = self.get_document()

        if document.fork_of is not None:
            signal = fork_delete
        else:
            signal = document_delete

        signal.send(sender=self, instance=self.get_document())

        resource = DocumentResource()
        resource.obj_delete(pk=self.kwargs.get("slug"))

        return HttpNoContent()

    def is_authorized(self):
        return self.get_document().is_editable(user_id=self.request.user.id)

    def redirect(self):
        return http.HttpResponseRedirect(
            reverse("show_document", kwargs=self.kwargs))

    def get_context_data(self, **kwargs):
        context = super(DocumentEditView, self).get_context_data(**kwargs)
        context["edit"] = True
        context["FIELD_TYPES"] = FIELD_TYPES
        context["SOCKETIO_HOST"] = settings.SOCKETIO_HOST
        return context


class NewDocumentView(LoginRequiredMixin, FormView):
    form_class = DocumentForm
    template_name = "documents/new.html"

    def form_valid(self, form, **kwargs):
        self.object_id = Document.objects.collection.insert({
            "title": form.cleaned_data.get("title"),
            "user_id": self.request.user.pk,
            "date_created": datetime.now(),
            "entities": form.cleaned_data.get("entities"),
            "is_public": form.cleaned_data.get("is_public"),
            "_keywords": extract_keywords(form.cleaned_data.get("title"))
        })
        document = Document.objects.get(_id=ObjectId(self.object_id))
        document_done.send(sender=self, instance=document)
        return super(NewDocumentView, self).form_valid(form)

    def get_success_url(self):
        return reverse("edit_document", args=[self.object_id])


class MyDocumentsView(LoginRequiredMixin, TemplateView):
    template_name = "documents/list.html"

    def get_context_data(self, **kwargs):
        return {
            "documents": self.get_documents(),
            "shared": self.get_shared_documents()
        }

    def get_documents(self):
        collection = Document.objects.for_user(self.request.user.id)
        return map(Document, collection)

    def get_shared_documents(self):
        collection = Document.objects.assigned(self.request.user.id)
        return map(Document, collection)


class SearchDocumentView(ListView):
    template_name = "documents/search.html"
    context_object_name = "documents"

    def get_queryset(self):
        form = self.get_form()

        if not form.is_valid():
            return []

        keyword = form.cleaned_data.get("keyword")
        collection = Document.objects.collection.find({
            "_keywords": {"$all": keyword.split()}})

        return map(Document, collection)

    def get_context_data(self, **kwargs):
        return super(SearchDocumentView, self).get_context_data(
            search_form=self.form,
            keyword=self.request.GET.get("keyword"),
            **kwargs)

    def get_form(self):
        self.form = SearchForm(self.request.GET)
        return self.form


class ForkDocumentView(DocumentMixin, NewDocumentView):
    form_class = ForkDocumentForm
    template_name = "documents/fork.html"

    def get_initial(self):
        return {
            "title": self.get_document().title
        }

    def form_valid(self, form, **kwargs):
        document = self.get_document()

        self.object_id = Document.objects.collection.insert({
            "title": form.cleaned_data.get("title"),
            "user_id": self.request.user.pk,
            "entities": document.entities,
            "fork_of": document.pk,
            "date_created": datetime.now(),
            "is_public": document.is_public,
            "_keywords": extract_keywords(form.cleaned_data.get("title"))
        })

        Document.objects.collection.update(
            {'_id': ObjectId(document.pk)},
            {"$inc": {'fork_count': 1}})

        document = Document.objects.get(_id=ObjectId(self.object_id))
        fork_done.send(sender=self, instance=document)

web/dbpatterns/dbpatterns/templates/documents/app.html
{% extends "documents/base.html" %}
{% load compress %}

{% block extra-head %}
    <link rel="stylesheet" href="{{ STATIC_URL }}css/autocomplete.css" />
{% endblock %}

{% block content %}

    <article id="document">
        <header role="banner" id="banner">
            {% block tools %}
                <nav class="tools">
                    <ul>
                        <li><a href="#" class="new-entity">New entity</a></li>
                        <li><a href="#export-list" data-toggle="true">Export</a></li>
                        <li><a href="#" class="save-document">Save</a></li>
                    </ul>
                </nav>
            {% endblock %}
            {% block app-header %}
            {% if edit %}
            <h2 class="edit-document"><a class="icon gear" href="#edit">settings</a></h2>
            {% endif %}
            <h1 class="{% if edit %}edit-title{% endif %} document-title">{{ document.title }}</h1>
            {% endblock %}
            <nav class="leave">
                {% block nav %}
                    <ul>
                        <li><a href="{% url my_documents %}">Back to list</a></li>
                    </ul>
                {% endblock %}
            </nav>

        </header>

        <div id="entities"></div>

        <div id="notifications"></div>

        <ul id="export-list">
            {% for key, label in exporters %}
                <li><a target="_blank" class="export" href="{% url export_document document.pk key %}">{{ label }}</a></li>
            {% endfor %}
        </ul>

        <div id="comments">
            <div class="info no-comment">There are no comments yet.</div>
        </div>

    </article>


    <!-- templates -->

    {% block app %}

        <script type="text/html" id="message-template">
        <strong><%= _.escape(username) %>:</strong> <%= _.escape(body) %>
        </script>

        <script type="text/html" id="assignee-item-template">
            <div class="info">
                <img src="<%= avatar %>">
                <span><%= username %></span>
            </div>
            <div class="actions">
                <select class="permission">
                    <option value="can_view">Can View</option>
                    <option value="can_edit">Can Edit</option>
                </select>
                <a href="#" class="remove">Remove</a>
            </div>
        </script>

        <script type="text/html" id="assignees-template">
            <div class="assignees">
                <ul class="users">

                </ul>
                <p class="add-people">
                    <label for="user">Add people</label>
                    <input type="text" id="user" placeholder="Enter a name or email...">
                </p>
            </div>
        </script>

        <script type="text/html" id="document-edit-template">
            <form>
                <p>
                    <label for="name">Title</label>
                    <input type="text" name="title" id="title">
                </p>
                <p>
                    <label>The visibility of document</label>
                    <label for="is_public">
                        <input type="radio" name="is_public" value="true" id="is_public"> Public
                    </label>
                    <label for="is_private">
                        <input type="radio" name="is_public" value="false" id="is_private"> Private
                    </label>
                </p>

                <p>
                    <label>People who have access</label>
                    <input type="text" name="assignees" id="assignees">
                </p>

                <footer>
                    <input type="submit" class="anchor save" value="Save" >
                    <input type="button" class="anchor close" value="Close" >
                </footer>
            </form>
        </script>

        <script type="text/html" id="comment-form-template">
            {% if user.is_anonymous %}
            <div id="anonymous-user">
                <p>Please login to leave comment.</p>
                <a href="{% url auth_login %}">Login</a>
                <a href="{% url auth_registration %}">Register</a>
            </div>
            {% endif %}
            <fieldset{% if user.is_anonymous %} class="blury"{% endif %}>
                <textarea name="body" id="id_body" placeholder="Write a comment"></textarea>
                <input type="button" value="Close" class="anchor close">
                <input type="submit" value="Send" class="anchor">
            </fieldset>
        </script>

        <script type="text/html" id="comment-item-template">
            <a href="<%= profile_url %>" class="gravatar"><img src="<%= avatar_url %>" /></a>
            <p>
                <a href="<%= profile_url %>" class="username"><%= _.escape(username) %></a> <%= _.escape(body) %>
                <% if (has_delete_permission) { %>
                <a href="#" class="delete">delete</a>
                <% } %>
            </p>
        </script>

        <script type="text/html" id="attribute-form-template">
            <form action="#" class="attribute-form">
                <p>
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name">
                </p>

                <p>
                    <label for="type">Type</label>
                    <select name="type" id="type">
                        {% for type, label in FIELD_TYPES %}
                        <option value="{{ type }}">{{ label }}</option>
                        {% endfor %}
                    </select>
                </p>

                <p>
                    <input type="checkbox" name="is_primary_key" value="true" id="is_primary_key">
                    <label for="is_primary_key"> Primary key</label>
                </p>

                <p>
                    <input type="checkbox" name="is_foreign_key" value="true" id="is_foreign_key">
                    <label for="is_foreign_key">Foreign key</label>
                </p>

                <p class="foreign-key-details">
                    <label for="name">Entity</label>
                    <input type="text" name="foreign_key_entity" id="foreign_key_entity">
                </p>

                <p class="foreign-key-details">
                    <label for="name">Attribute</label>
                    <input type="text" name="foreign_key_attribute" id="foreign_key_attribute">
                </p>


                <input type="submit" class="anchor save" value="Save" >
                <input type="button" class="anchor close" value="Close" >

            </form>
        </script>

        <script type="text/html" id="attribute-list-template">
            <section class="attributes"></section>
            {% if edit %}<a href="#" class="action new-attribute">new attribute</a>{% endif %}
        </script>

        <script type="text/html" id="attribute-template">
            <a href="#" class="name {% if edit %}edit{% endif %}"><%= _.escape(name) %> <span><%= _.escape(type) %></span></a>
            {% if edit %}<a href="#" class="remove-attribute" title="remove attribute">delete</a>{% endif %}
        </script>

        <script type="text/html" id="entity-template">
            <header>
                <h3><%= _.escape(name) %></h3>
            </header>
            <section class="attributes"></section>

            <footer>
                {% if edit %}<a href="#" class="action remove-entity">remove entity</a>{% endif %}
            </footer>

        </script>

        <script type="text/html" id="dialog-template">
        <h3><%= _.escape(title) %></h3>
        </script>

        <script type="text/html" id="export-dialog-template">
            <h3><%= _.escape(title) %></h3>
            <pre class="prettyprint"><code><%= _.escape(code) %></code></pre>
            <a href="#" class="anchor close">Close</a>
            <a href="#" class="anchor new-window">Plain version</a>
        </script>

{% endblock %}

{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        // underscore.string mixin
        _.mixin(_.string.exports());
    </script>

    <!-- namespaces -->
    <script type="text/javascript">
        var dbpatterns = {
            models: {},
            collections: {},
            views: {},
            notifications: {}
        };
        _.extend(dbpatterns.notifications, Backbone.Events);
    </script>

    <!-- app  -->
    {% compress js %}
    <script src="{{ STATIC_URL }}js/models/document.js"></script>
    <script src="{{ STATIC_URL }}js/models/entity.js"></script>
    <script src="{{ STATIC_URL }}js/models/attribute.js"></script>
    <script src="{{ STATIC_URL }}js/models/comment.js"></script>
    <script src="{{ STATIC_URL }}js/models/assignee.js"></script>
    <script src="{{ STATIC_URL }}js/models/chat.js"></script>

    <!-- views -->
    <script src="{{ STATIC_URL }}js/views/ui.js"></script>
    <script src="{{ STATIC_URL }}js/views/document.js"></script>
    <script src="{{ STATIC_URL }}js/views/entity.js"></script>
    <script src="{{ STATIC_URL }}js/views/attribute.js"></script>
    <script src="{{ STATIC_URL }}js/views/connection.js"></script>
    <script src="{{ STATIC_URL }}js/views/comment.js"></script>
    <script src="{{ STATIC_URL }}js/views/notifier.js"></script>
    <script src="{{ STATIC_URL }}js/views/user.js"></script>
    <script src="{{ STATIC_URL }}js/views/chat.js"></script>
    {% endcompress %}

    <!-- bootstrap -->
    <script type="text/javascript">
        $(function () {

            // load notifier view.
            new dbpatterns.views.Notifier();

            // create a new document instance with resource uri.
            var document = new dbpatterns.models.Document({
                "resource_uri": "{{ document.get_resource_uri }}"
            }, {
                "socket_uri": "{{ SOCKETIO_HOST }}",
                "use_websocket": {{ edit|yesno:"true,false" }}
            });

            // load document view.
            new dbpatterns.views.Document({
                "model": document,
                "edit": {{ edit|yesno:"true,false" }}
            });

            // retrieve document by the provided resource uri.
            document.fetch({
                success: function () {
                    document.trigger("load");
                }
            });

            {% if edit %}
            // connect to the live server
            document.socket.emit("connect", {
                "document_id": "{{ document.id }}",
                "username": "{{ user.username }}"
            });
            {% endif %}

        });
    </script>
{% endblock %}

{% block footer %}{% endblock %}

web/dbpatterns/dbpatterns/templates/documents/base.html
{% extends "base.html" %}


{% block header %}
{% endblock %}

web/dbpatterns/dbpatterns/templates/documents/edit.html
{% extends "documents/app.html" %}


{% block body-id %}document-edit-view{% endblock %}

{% block nav %}
    <ul>
        <li><a href="{% url my_documents %}">Back to list</a></li>
        <li><a class="show" href="{% url show_document document.pk %}">Show</a></li>
    </ul>
{% endblock %}

{% block content %}
{{ block.super }}
<div id="help">
    <div id="help-content">
        <h3>Shortcuts</h3>
        <ul>
            <li>OPTION+N: Create new entity</li>
            <li>OPTION+R: Rename document</li>
            <li>OPTION+S: Save document</li>
        </ul>
        <h3>Auto-fill conditions</h3>
        <ul>
            <li>Columns that named "id": integer type.</li>
            <li>Columns that starts with "_is": boolean type.</li>
            <li>Columns that starts with or ends with "date": datetime type.</li>
            <li>Columns that consist with table name, underscore and column name: foreign key.</li>
        </ul>
    </div>
    <a href="#help-content" id="help-button" data-toggle="true" class="button">Help</a>
</div>
<div id="chat">
    <aside></aside>
    <section>
        <ul></ul>
    </section>
    <footer></footer>
</div>
<a href="#chat" id="chat-button" data-toggle="true" class="button">
    Online: <span id="online-count">2</span>
</a>
{% endblock %}

web/dbpatterns/dbpatterns/templates/documents/fork.html
{% extends "base.html" %}

{% block content %}
    <section class="new-document content">
        <h2>Fork Document</h2>
        <form action="{% url fork_document document_id %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Fork">
        </form>
    </section>
{% endblock %}

web/dbpatterns/dbpatterns/templates/documents/new.html
{% extends "base.html" %}

{% block content %}
    <section class="new-document content">
        <h2>New Document</h2>
        <form action="{% url new_document %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <p class="buttons">
                <input type="submit" class="anchor" value="Create">
            </p>
        </form>
    </section>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript">
        $(function () {
            var row = $("#id_entities").parent().hide();
            $("#id_create_from").change(function () {
                if ($(this).val()) {
                    row.show();
                } else {
                    row.hide()
                }
            }).change();
        });
    </script>
{% endblock %}

web/dbpatterns/dbpatterns/templates/documents/search_form.html
<form id="search-form" action="{% url search_document %}" method="get">
    {{ search_form.as_p }}
    <p><input type="submit" value="Search" class="button"></p>
</form>